# Generated by Django 4.2.2 on 2024-09-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_eval_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('CLASS ONE', 'Class One'), ('CLASS TWO', 'Class Two'), ('CLASS THREE', 'Class Three')], default='CLASS ONE', max_length=255, null=True),
        ),
    ]
